version: "3.7"
services:
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - "./nginx.conf:/etc/nginx/nginx.conf:ro"
  #   ports:
  #     - 80:80
  #     - 443:443
  #   links:
  #     - "jupyter"
  jupyter:
    image: jupyter/all-spark-notebook
    container_name: jupyter
    ports:
      - 443:8888
    volumes:
      - "./jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py:ro"
